### ISSUE TITLE
mac 10.9.1获取不到通讯录信息

### ISSUE THREAD

**Issue by AmazingCaddy** [lexrus/PhoneticContacts#1]
我在xocde下debug了一下，发现取出来的通讯录是空的

**Comment by lexrus** [comment]
我在 10.9.1 下试了一下，确定可以。

你看一下你系统的通讯录里有没有联系人。

**Comment by AmazingCaddy** [comment]
有的有好几百，访问通讯录，应该需要授权的，系统没有提示我授权-_-#

**Comment by AmazingCaddy** [comment]
不知道怎么回事啊，ObjectC也不懂，只是发现ab的值是nil
