### ISSUE TITLE
使用后输入法不能打出名字

### ISSUE THREAD

**Issue by iplus26** [lexrus/PhoneticContacts#4]
使用后原生输入法不能打出名字，iOS 9.2

**Comment by lexrus** [comment]
原生输入法有检索通讯录名字的功能吗？我不知道。

**Comment by iplus26** [comment]
有的，参考这个[视频](https://youtu.be/FwAGoDLlRl4)，本来我的手机是不能打出“李圆拔”这个（我瞎编的）名字，但是在创建了这个联系人之后，就可以打出“李圆拔”（在第二个候选词）。

而在使用之后就不能正确打出通讯录中的名字。

<del>我的建议是：使用汉语拼音**不加声调**是可以正常使用原生输入法打出名字的，并且也可以在英文系统下正确显示排序。</del>Update: 见下面的更新

**Comment by lexrus** [comment]
哦，去声调我有注释，你把这一行前的 `//` 去掉再运行一下就去声调了：
https://github.com/lexrus/PhoneticContacts/blob/master/PhoneticContacts/main.m#L27

**Comment by iplus26** [comment]
抱歉，我尝试了一下不加音调，后来发现其实是因为如果这个人是两个字的名字（连姓三个字，比如“李圆拔”），不能在名字的两个注音有空格，比如

`yuán bá // not work`
`yuan ba // not work`
`yuanba // work`
`yuánbá // work`

音调其实对这个没有影响

**Comment by lexrus** [comment]
空格倒是可以去掉，但是打 `liyuanbo` 或者 `lyb` 还能出来这个人吗？

**Comment by iplus26** [comment]
我刚刚又重新测了一下，如果在英文系统下的话，打`liyuanba`是可以出来的，但是`lyb`自然就不行。在中文系统下，打`liyuanba`或者`lyb`都是可以的。

**Comment by lexrus** [comment]
汗。。。那这个 bug 是自动修复了？

**Comment by iplus26** [comment]
不不，我是说**将空格去掉之后**如果在英文系统下的话，打`liyuanba`是可以出来的，但是`lyb`自然就不行；在中文系统下，打`liyuanba`或者`lyb`都是可以的。

**Comment by lexrus** [comment]
好，那我晚点加上去掉空格的部分。

**Comment by iplus26** [comment]
Thx

**Comment by lexrus** [comment]
已经修正。请更新一下代码再运行一遍。

**Comment by iplus26** [comment]
应该没有问题了 thx
