### ISSUE TITLE
Still failed in 10.11.3

### ISSUE THREAD

**Issue by iPatrickW** [lexrus/PhoneticContacts#7]
![2016-02-08 4 14 24](https://cloud.githubusercontent.com/assets/10046631/12880803/23e03a0a-ce7f-11e5-82ab-dcc39137b78c.png)
![2016-02-08 4 15 30](https://cloud.githubusercontent.com/assets/10046631/12880808/371caaae-ce7f-11e5-9336-7acd6936397b.png)

**Comment by zkzipoo** [comment]
are you using the lasted Swift version

**Comment by lexrus** [comment]
Please upgrade Xcode to 7.2.1.
